/*
 * foods.js — built-in food database.
 *
 * All values are per 100 g (edible portion): kcal, protein (g), carbs (g),
 * fat (g). Figures are rounded reference values derived from USDA FoodData
 * Central (https://fdc.nal.usda.gov/), a U.S. government work in the public
 * domain. They are typical values for the named food, not for any brand.
 * Every row is checked by the test suite for 4/4/9 energy consistency.
 */
"use strict";

const BUILTIN_FOODS = [
  // ---------- Fruits ----------
  { id: "apple", name: "Apple (raw, with skin)", kcal: 52, protein: 0.3, carbs: 13.8, fat: 0.2 },
  { id: "banana", name: "Banana (raw)", kcal: 89, protein: 1.1, carbs: 22.8, fat: 0.3 },
  { id: "orange", name: "Orange (raw)", kcal: 47, protein: 0.9, carbs: 11.8, fat: 0.1 },
  { id: "strawberries", name: "Strawberries (raw)", kcal: 32, protein: 0.7, carbs: 7.7, fat: 0.3 },
  { id: "blueberries", name: "Blueberries (raw)", kcal: 57, protein: 0.7, carbs: 14.5, fat: 0.3 },
  { id: "raspberries", name: "Raspberries (raw)", kcal: 52, protein: 1.2, carbs: 11.9, fat: 0.7 },
  { id: "blackberries", name: "Blackberries (raw)", kcal: 43, protein: 1.4, carbs: 9.6, fat: 0.5 },
  { id: "grapes", name: "Grapes (raw)", kcal: 69, protein: 0.7, carbs: 18.1, fat: 0.2 },
  { id: "watermelon", name: "Watermelon (raw)", kcal: 30, protein: 0.6, carbs: 7.6, fat: 0.2 },
  { id: "cantaloupe", name: "Cantaloupe (raw)", kcal: 34, protein: 0.8, carbs: 8.2, fat: 0.2 },
  { id: "pineapple", name: "Pineapple (raw)", kcal: 50, protein: 0.5, carbs: 13.1, fat: 0.1 },
  { id: "mango", name: "Mango (raw)", kcal: 60, protein: 0.8, carbs: 15.0, fat: 0.4 },
  { id: "peach", name: "Peach (raw)", kcal: 39, protein: 0.9, carbs: 9.5, fat: 0.3 },
  { id: "pear", name: "Pear (raw)", kcal: 57, protein: 0.4, carbs: 15.2, fat: 0.1 },
  { id: "plum", name: "Plum (raw)", kcal: 46, protein: 0.7, carbs: 11.4, fat: 0.3 },
  { id: "cherries", name: "Cherries (sweet, raw)", kcal: 63, protein: 1.1, carbs: 16.0, fat: 0.2 },
  { id: "kiwi", name: "Kiwi fruit (raw)", kcal: 61, protein: 1.1, carbs: 14.7, fat: 0.5 },
  { id: "avocado", name: "Avocado (raw)", kcal: 160, protein: 2.0, carbs: 8.5, fat: 14.7 },
  { id: "grapefruit", name: "Grapefruit (raw)", kcal: 42, protein: 0.8, carbs: 10.7, fat: 0.1 },
  { id: "lemon", name: "Lemon (raw)", kcal: 29, protein: 1.1, carbs: 9.3, fat: 0.3 },
  { id: "raisins", name: "Raisins", kcal: 299, protein: 3.1, carbs: 79.2, fat: 0.5 },
  { id: "dates", name: "Dates (Medjool)", kcal: 277, protein: 1.8, carbs: 75.0, fat: 0.2 },
  { id: "applesauce", name: "Applesauce (unsweetened)", kcal: 42, protein: 0.2, carbs: 11.3, fat: 0.1 },
  { id: "fruit_cocktail", name: "Fruit cocktail (canned in juice)", kcal: 45, protein: 0.5, carbs: 11.9, fat: 0.0 },
  { id: "pomegranate", name: "Pomegranate (raw)", kcal: 83, protein: 1.7, carbs: 18.7, fat: 1.2 },

  // ---------- Vegetables ----------
  { id: "broccoli", name: "Broccoli (cooked)", kcal: 35, protein: 2.4, carbs: 7.2, fat: 0.4 },
  { id: "carrot", name: "Carrot (raw)", kcal: 41, protein: 0.9, carbs: 9.6, fat: 0.2 },
  { id: "spinach", name: "Spinach (raw)", kcal: 23, protein: 2.9, carbs: 3.6, fat: 0.4 },
  { id: "spinach_cooked", name: "Spinach (cooked)", kcal: 23, protein: 3.0, carbs: 3.8, fat: 0.3 },
  { id: "tomato", name: "Tomato (raw)", kcal: 18, protein: 0.9, carbs: 3.9, fat: 0.2 },
  { id: "potato_baked", name: "Potato (baked, with skin)", kcal: 93, protein: 2.5, carbs: 21.2, fat: 0.1 },
  { id: "potato_mashed", name: "Mashed potatoes (with milk & butter)", kcal: 113, protein: 2.0, carbs: 16.8, fat: 4.2 },
  { id: "sweet_potato", name: "Sweet potato (baked)", kcal: 90, protein: 2.0, carbs: 20.7, fat: 0.2 },
  { id: "cucumber", name: "Cucumber (raw)", kcal: 15, protein: 0.7, carbs: 3.6, fat: 0.1 },
  { id: "lettuce", name: "Lettuce (romaine, raw)", kcal: 17, protein: 1.2, carbs: 3.3, fat: 0.3 },
  { id: "lettuce_iceberg", name: "Lettuce (iceberg, raw)", kcal: 14, protein: 0.9, carbs: 3.0, fat: 0.1 },
  { id: "kale", name: "Kale (raw)", kcal: 35, protein: 2.9, carbs: 4.4, fat: 1.5 },
  { id: "cauliflower", name: "Cauliflower (cooked)", kcal: 23, protein: 1.8, carbs: 4.1, fat: 0.5 },
  { id: "brussels_sprouts", name: "Brussels sprouts (cooked)", kcal: 36, protein: 2.6, carbs: 7.1, fat: 0.5 },
  { id: "green_beans", name: "Green beans (cooked)", kcal: 35, protein: 1.9, carbs: 7.9, fat: 0.3 },
  { id: "peas", name: "Green peas (cooked)", kcal: 84, protein: 5.4, carbs: 15.6, fat: 0.2 },
  { id: "corn", name: "Corn (sweet, cooked)", kcal: 96, protein: 3.4, carbs: 21.0, fat: 1.5 },
  { id: "bell_pepper", name: "Bell pepper (red, raw)", kcal: 31, protein: 1.0, carbs: 6.0, fat: 0.3 },
  { id: "onion", name: "Onion (raw)", kcal: 40, protein: 1.1, carbs: 9.3, fat: 0.1 },
  { id: "garlic", name: "Garlic (raw)", kcal: 149, protein: 6.4, carbs: 33.1, fat: 0.5 },
  { id: "mushrooms", name: "Mushrooms (white, raw)", kcal: 22, protein: 3.1, carbs: 3.3, fat: 0.3 },
  { id: "zucchini", name: "Zucchini (cooked)", kcal: 15, protein: 1.1, carbs: 2.7, fat: 0.4 },
  { id: "asparagus", name: "Asparagus (cooked)", kcal: 22, protein: 2.4, carbs: 4.1, fat: 0.2 },
  { id: "celery", name: "Celery (raw)", kcal: 14, protein: 0.7, carbs: 3.0, fat: 0.2 },
  { id: "cabbage", name: "Cabbage (raw)", kcal: 25, protein: 1.3, carbs: 5.8, fat: 0.1 },
  { id: "beets", name: "Beets (cooked)", kcal: 44, protein: 1.7, carbs: 10.0, fat: 0.2 },
  { id: "eggplant", name: "Eggplant (cooked)", kcal: 35, protein: 0.8, carbs: 8.7, fat: 0.2 },
  { id: "butternut_squash", name: "Butternut squash (baked)", kcal: 40, protein: 0.9, carbs: 10.5, fat: 0.1 },
  { id: "pumpkin", name: "Pumpkin (canned)", kcal: 34, protein: 1.1, carbs: 8.1, fat: 0.3 },
  { id: "coleslaw_mix", name: "Coleslaw (with dressing)", kcal: 153, protein: 1.2, carbs: 13.5, fat: 10.7 },
  { id: "edamame", name: "Edamame (cooked)", kcal: 121, protein: 11.9, carbs: 8.9, fat: 5.2 },
  { id: "salsa", name: "Salsa", kcal: 29, protein: 1.5, carbs: 6.3, fat: 0.2 },
  { id: "pickles", name: "Dill pickles", kcal: 11, protein: 0.3, carbs: 2.3, fat: 0.2 },
  { id: "olives", name: "Olives (black, canned)", kcal: 115, protein: 0.8, carbs: 6.3, fat: 10.7 },

  // ---------- Grains, bread & cereal ----------
  { id: "rice_white", name: "White rice (cooked)", kcal: 130, protein: 2.7, carbs: 28.2, fat: 0.3 },
  { id: "rice_brown", name: "Brown rice (cooked)", kcal: 123, protein: 2.7, carbs: 25.6, fat: 1.0 },
  { id: "pasta", name: "Pasta (cooked)", kcal: 158, protein: 5.8, carbs: 30.9, fat: 0.9 },
  { id: "pasta_whole", name: "Whole-wheat pasta (cooked)", kcal: 149, protein: 6.3, carbs: 30.4, fat: 1.7 },
  { id: "bread_white", name: "White bread", kcal: 266, protein: 8.9, carbs: 49.4, fat: 3.3 },
  { id: "bread_whole", name: "Whole-wheat bread", kcal: 247, protein: 13.0, carbs: 41.3, fat: 3.4 },
  { id: "bread_sourdough", name: "Sourdough bread", kcal: 272, protein: 10.8, carbs: 51.9, fat: 2.4 },
  { id: "bagel", name: "Bagel (plain)", kcal: 257, protein: 10.0, carbs: 50.5, fat: 1.7 },
  { id: "english_muffin", name: "English muffin", kcal: 232, protein: 9.1, carbs: 45.4, fat: 1.7 },
  { id: "croissant", name: "Croissant (butter)", kcal: 406, protein: 8.2, carbs: 45.8, fat: 21.0 },
  { id: "oats", name: "Oatmeal (cooked with water)", kcal: 71, protein: 2.5, carbs: 12.0, fat: 1.5 },
  { id: "oats_dry", name: "Oats (dry, rolled)", kcal: 379, protein: 13.2, carbs: 67.7, fat: 6.5 },
  { id: "quinoa", name: "Quinoa (cooked)", kcal: 120, protein: 4.4, carbs: 21.3, fat: 1.9 },
  { id: "couscous", name: "Couscous (cooked)", kcal: 112, protein: 3.8, carbs: 23.2, fat: 0.2 },
  { id: "tortilla", name: "Flour tortilla", kcal: 306, protein: 8.2, carbs: 50.4, fat: 7.8 },
  { id: "tortilla_corn", name: "Corn tortilla", kcal: 218, protein: 5.7, carbs: 44.6, fat: 2.9 },
  { id: "cereal_toasted_oat", name: "Toasted oat cereal rings", kcal: 379, protein: 12.1, carbs: 73.2, fat: 6.7 },
  { id: "cereal_corn_flakes", name: "Corn flakes cereal", kcal: 357, protein: 7.5, carbs: 84.1, fat: 0.4 },
  { id: "cereal_raisin_bran", name: "Raisin bran cereal", kcal: 327, protein: 8.3, carbs: 79.2, fat: 1.6 },
  { id: "cereal_frosted_flakes", name: "Frosted corn flakes cereal", kcal: 375, protein: 4.5, carbs: 89.0, fat: 0.5 },
  { id: "cereal_granola", name: "Granola", kcal: 471, protein: 10.0, carbs: 64.0, fat: 20.0 },
  { id: "grits", name: "Grits (cooked)", kcal: 59, protein: 1.4, carbs: 12.8, fat: 0.2 },
  { id: "pancake", name: "Pancakes (from mix)", kcal: 227, protein: 6.4, carbs: 28.3, fat: 9.7 },
  { id: "waffle", name: "Waffle (frozen, toasted)", kcal: 291, protein: 6.6, carbs: 45.0, fat: 9.5 },
  { id: "french_toast", name: "French toast", kcal: 229, protein: 7.7, carbs: 25.0, fat: 11.0 },
  { id: "crackers_saltine", name: "Saltine crackers", kcal: 421, protein: 9.5, carbs: 74.3, fat: 8.6 },
  { id: "crackers_wheat", name: "Wheat crackers", kcal: 473, protein: 8.0, carbs: 65.0, fat: 20.0 },
  { id: "rice_cake", name: "Rice cakes (plain)", kcal: 387, protein: 8.2, carbs: 81.5, fat: 2.8 },
  { id: "barley", name: "Barley (pearled, cooked)", kcal: 123, protein: 2.3, carbs: 28.2, fat: 0.4 },
  { id: "ramen", name: "Ramen noodles (prepared)", kcal: 188, protein: 4.5, carbs: 27.0, fat: 7.0 },
  { id: "mac_and_cheese", name: "Macaroni and cheese (prepared)", kcal: 164, protein: 6.7, carbs: 20.1, fat: 6.6 },
  { id: "stuffing", name: "Bread stuffing (prepared)", kcal: 195, protein: 3.6, carbs: 19.4, fat: 11.8 },
  { id: "biscuit", name: "Biscuit (plain)", kcal: 353, protein: 7.0, carbs: 45.1, fat: 16.3 },
  { id: "cornbread", name: "Cornbread", kcal: 330, protein: 7.3, carbs: 51.1, fat: 10.6 },
  { id: "hamburger_bun", name: "Hamburger bun", kcal: 279, protein: 9.5, carbs: 49.9, fat: 4.2 },

  // ---------- Meat, poultry & fish ----------
  { id: "chicken_breast", name: "Chicken breast (roasted, skinless)", kcal: 165, protein: 31.0, carbs: 0.0, fat: 3.6 },
  { id: "chicken_thigh", name: "Chicken thigh (roasted, skinless)", kcal: 209, protein: 26.0, carbs: 0.0, fat: 10.9 },
  { id: "chicken_wing", name: "Chicken wings (roasted, with skin)", kcal: 290, protein: 26.9, carbs: 0.0, fat: 19.5 },
  { id: "chicken_drumstick", name: "Chicken drumstick (roasted, with skin)", kcal: 216, protein: 27.0, carbs: 0.0, fat: 11.2 },
  { id: "chicken_ground", name: "Ground chicken (cooked)", kcal: 189, protein: 23.3, carbs: 0.0, fat: 10.2 },
  { id: "chicken_rotisserie", name: "Rotisserie chicken (meat only)", kcal: 205, protein: 24.0, carbs: 0.0, fat: 11.7 },
  { id: "chicken_nuggets", name: "Chicken nuggets", kcal: 296, protein: 15.5, carbs: 14.0, fat: 19.8 },
  { id: "chicken_tenders_fried", name: "Chicken tenders (breaded, fried)", kcal: 271, protein: 18.5, carbs: 17.5, fat: 14.0 },
  { id: "turkey_breast", name: "Turkey breast (roasted)", kcal: 147, protein: 30.1, carbs: 0.0, fat: 2.1 },
  { id: "turkey_ground", name: "Ground turkey (93% lean, cooked)", kcal: 213, protein: 27.1, carbs: 0.0, fat: 11.6 },
  { id: "turkey_deli", name: "Turkey deli slices", kcal: 104, protein: 17.1, carbs: 4.2, fat: 1.7 },
  { id: "beef_ground", name: "Ground beef (85% lean, cooked)", kcal: 250, protein: 25.9, carbs: 0.0, fat: 15.4 },
  { id: "beef_ground_93", name: "Ground beef (93% lean, cooked)", kcal: 182, protein: 25.6, carbs: 0.0, fat: 8.2 },
  { id: "steak", name: "Beef sirloin steak (grilled)", kcal: 212, protein: 29.0, carbs: 0.0, fat: 9.9 },
  { id: "steak_ribeye", name: "Ribeye steak (grilled)", kcal: 291, protein: 24.0, carbs: 0.0, fat: 21.0 },
  { id: "beef_roast", name: "Beef chuck roast (braised)", kcal: 282, protein: 26.4, carbs: 0.0, fat: 18.8 },
  { id: "beef_deli", name: "Roast beef deli slices", kcal: 115, protein: 18.6, carbs: 0.6, fat: 3.8 },
  { id: "pork_chop", name: "Pork chop (grilled)", kcal: 231, protein: 27.3, carbs: 0.0, fat: 12.8 },
  { id: "pork_tenderloin", name: "Pork tenderloin (roasted)", kcal: 143, protein: 26.2, carbs: 0.0, fat: 3.5 },
  { id: "pork_ribs", name: "Pork spare ribs (roasted)", kcal: 397, protein: 29.1, carbs: 0.0, fat: 30.3 },
  { id: "pulled_pork", name: "Pulled pork (with BBQ sauce)", kcal: 210, protein: 18.5, carbs: 11.0, fat: 9.5 },
  { id: "bacon", name: "Bacon (cooked)", kcal: 541, protein: 37.0, carbs: 1.4, fat: 41.8 },
  { id: "ham", name: "Ham (sliced, lean)", kcal: 145, protein: 20.9, carbs: 1.5, fat: 5.5 },
  { id: "sausage_pork", name: "Pork breakfast sausage (cooked)", kcal: 325, protein: 18.5, carbs: 1.4, fat: 27.3 },
  { id: "hot_dog", name: "Hot dog (beef frank)", kcal: 322, protein: 11.2, carbs: 2.7, fat: 29.4 },
  { id: "pepperoni", name: "Pepperoni", kcal: 504, protein: 19.3, carbs: 1.2, fat: 46.3 },
  { id: "salami", name: "Salami (hard)", kcal: 407, protein: 22.6, carbs: 1.6, fat: 33.7 },
  { id: "lamb_chop", name: "Lamb chop (grilled)", kcal: 294, protein: 25.0, carbs: 0.0, fat: 21.0 },
  { id: "salmon", name: "Salmon (baked)", kcal: 206, protein: 22.1, carbs: 0.0, fat: 12.4 },
  { id: "salmon_canned", name: "Salmon (canned)", kcal: 167, protein: 23.1, carbs: 0.0, fat: 7.8 },
  { id: "tuna_canned", name: "Tuna (canned in water, drained)", kcal: 116, protein: 25.5, carbs: 0.0, fat: 0.8 },
  { id: "tuna_steak", name: "Tuna steak (grilled)", kcal: 132, protein: 29.9, carbs: 0.0, fat: 1.3 },
  { id: "tilapia", name: "Tilapia (baked)", kcal: 128, protein: 26.2, carbs: 0.0, fat: 2.7 },
  { id: "cod", name: "Cod (baked)", kcal: 105, protein: 22.8, carbs: 0.0, fat: 0.9 },
  { id: "shrimp", name: "Shrimp (cooked)", kcal: 99, protein: 24.0, carbs: 0.2, fat: 0.3 },
  { id: "crab", name: "Crab meat (cooked)", kcal: 97, protein: 19.4, carbs: 0.0, fat: 1.5 },
  { id: "fish_sticks", name: "Fish sticks (baked)", kcal: 249, protein: 11.0, carbs: 21.5, fat: 13.0 },
  { id: "sardines", name: "Sardines (canned in oil, drained)", kcal: 208, protein: 24.6, carbs: 0.0, fat: 11.5 },

  // ---------- Eggs, dairy & alternatives ----------
  { id: "egg", name: "Egg (whole, cooked)", kcal: 155, protein: 12.6, carbs: 1.1, fat: 10.6 },
  { id: "egg_white", name: "Egg whites (cooked)", kcal: 52, protein: 10.9, carbs: 0.7, fat: 0.2 },
  { id: "egg_scrambled", name: "Scrambled eggs (with milk & butter)", kcal: 149, protein: 10.0, carbs: 1.6, fat: 11.0 },
  { id: "milk_whole", name: "Milk (whole)", kcal: 61, protein: 3.2, carbs: 4.8, fat: 3.3 },
  { id: "milk_2pct", name: "Milk (2%)", kcal: 50, protein: 3.3, carbs: 4.8, fat: 2.0 },
  { id: "milk_skim", name: "Milk (skim)", kcal: 34, protein: 3.4, carbs: 5.0, fat: 0.1 },
  { id: "milk_almond", name: "Almond milk (unsweetened)", kcal: 15, protein: 0.6, carbs: 0.6, fat: 1.2 },
  { id: "milk_soy", name: "Soy milk (unsweetened)", kcal: 41, protein: 3.5, carbs: 1.7, fat: 2.2 },
  { id: "milk_oat", name: "Oat milk", kcal: 48, protein: 1.0, carbs: 7.0, fat: 1.5 },
  { id: "yogurt_greek", name: "Greek yogurt (plain, nonfat)", kcal: 59, protein: 10.2, carbs: 3.6, fat: 0.4 },
  { id: "yogurt_greek_whole", name: "Greek yogurt (plain, whole milk)", kcal: 97, protein: 9.0, carbs: 3.9, fat: 5.0 },
  { id: "yogurt_fruit", name: "Yogurt (lowfat, fruit flavored)", kcal: 99, protein: 3.9, carbs: 18.6, fat: 1.1 },
  { id: "cheese_cheddar", name: "Cheddar cheese", kcal: 403, protein: 24.9, carbs: 1.3, fat: 33.1 },
  { id: "cheese_mozzarella", name: "Mozzarella (part-skim)", kcal: 254, protein: 24.3, carbs: 2.8, fat: 15.9 },
  { id: "cheese_swiss", name: "Swiss cheese", kcal: 380, protein: 26.9, carbs: 5.4, fat: 27.8 },
  { id: "cheese_american", name: "American cheese (processed)", kcal: 297, protein: 15.9, carbs: 8.7, fat: 22.3 },
  { id: "cheese_parmesan", name: "Parmesan (grated)", kcal: 420, protein: 28.4, carbs: 13.9, fat: 27.8 },
  { id: "cheese_cream", name: "Cream cheese", kcal: 342, protein: 5.9, carbs: 4.1, fat: 34.2 },
  { id: "cheese_string", name: "String cheese (mozzarella)", kcal: 280, protein: 24.0, carbs: 4.0, fat: 18.0 },
  { id: "cottage_cheese", name: "Cottage cheese (2%)", kcal: 84, protein: 11.0, carbs: 4.3, fat: 2.3 },
  { id: "butter", name: "Butter", kcal: 717, protein: 0.9, carbs: 0.1, fat: 81.1 },
  { id: "margarine", name: "Margarine (stick)", kcal: 717, protein: 0.2, carbs: 0.9, fat: 80.5 },
  { id: "sour_cream", name: "Sour cream", kcal: 198, protein: 2.4, carbs: 4.6, fat: 19.4 },
  { id: "heavy_cream", name: "Heavy whipping cream", kcal: 340, protein: 2.8, carbs: 2.7, fat: 36.1 },
  { id: "half_and_half", name: "Half and half", kcal: 131, protein: 3.1, carbs: 4.3, fat: 11.5 },
  { id: "ice_cream_vanilla", name: "Ice cream (vanilla)", kcal: 207, protein: 3.5, carbs: 23.6, fat: 11.0 },
  { id: "frozen_yogurt", name: "Frozen yogurt (vanilla)", kcal: 159, protein: 4.0, carbs: 24.4, fat: 5.6 },
  { id: "whipped_cream", name: "Whipped cream (aerosol)", kcal: 257, protein: 3.2, carbs: 12.5, fat: 22.2 },

  // ---------- Beans, tofu & plant protein ----------
  { id: "tofu", name: "Tofu (firm)", kcal: 78, protein: 9.0, carbs: 2.3, fat: 4.2 },
  { id: "tempeh", name: "Tempeh", kcal: 192, protein: 20.3, carbs: 7.6, fat: 10.8 },
  { id: "beans_black", name: "Black beans (cooked)", kcal: 132, protein: 8.9, carbs: 23.7, fat: 0.5 },
  { id: "beans_kidney", name: "Kidney beans (cooked)", kcal: 127, protein: 8.7, carbs: 22.8, fat: 0.5 },
  { id: "beans_pinto", name: "Pinto beans (cooked)", kcal: 143, protein: 9.0, carbs: 26.2, fat: 0.7 },
  { id: "beans_refried", name: "Refried beans (canned)", kcal: 91, protein: 5.4, carbs: 15.1, fat: 1.2 },
  { id: "beans_baked", name: "Baked beans (canned)", kcal: 105, protein: 4.8, carbs: 20.5, fat: 0.9 },
  { id: "chickpeas", name: "Chickpeas (cooked)", kcal: 164, protein: 8.9, carbs: 27.4, fat: 2.6 },
  { id: "hummus", name: "Hummus", kcal: 166, protein: 7.9, carbs: 14.3, fat: 9.6 },
  { id: "lentils", name: "Lentils (cooked)", kcal: 116, protein: 9.0, carbs: 20.1, fat: 0.4 },
  { id: "veggie_burger", name: "Veggie burger patty", kcal: 177, protein: 15.7, carbs: 13.5, fat: 7.0 },
  { id: "protein_shake", name: "Whey protein powder", kcal: 375, protein: 75.0, carbs: 12.5, fat: 5.0 },
  { id: "protein_bar", name: "Protein bar (typical)", kcal: 380, protein: 30.0, carbs: 40.0, fat: 12.0 },

  // ---------- Nuts, seeds & oils ----------
  { id: "almonds", name: "Almonds (raw)", kcal: 579, protein: 21.2, carbs: 21.6, fat: 49.9 },
  { id: "peanuts", name: "Peanuts (roasted, salted)", kcal: 587, protein: 24.4, carbs: 21.3, fat: 49.7 },
  { id: "peanut_butter", name: "Peanut butter (smooth)", kcal: 588, protein: 25.1, carbs: 19.6, fat: 50.4 },
  { id: "almond_butter", name: "Almond butter", kcal: 614, protein: 21.0, carbs: 18.8, fat: 55.5 },
  { id: "walnuts", name: "Walnuts", kcal: 654, protein: 15.2, carbs: 13.7, fat: 65.2 },
  { id: "cashews", name: "Cashews (roasted)", kcal: 574, protein: 15.3, carbs: 32.7, fat: 46.4 },
  { id: "pistachios", name: "Pistachios (roasted)", kcal: 572, protein: 21.0, carbs: 28.3, fat: 45.8 },
  { id: "pecans", name: "Pecans", kcal: 691, protein: 9.2, carbs: 13.9, fat: 72.0 },
  { id: "sunflower_seeds", name: "Sunflower seeds (roasted)", kcal: 582, protein: 19.3, carbs: 24.1, fat: 49.8 },
  { id: "chia_seeds", name: "Chia seeds", kcal: 486, protein: 16.5, carbs: 42.1, fat: 30.7 },
  { id: "flax_seeds", name: "Flax seeds (ground)", kcal: 534, protein: 18.3, carbs: 28.9, fat: 42.2 },
  { id: "trail_mix", name: "Trail mix (with chocolate)", kcal: 462, protein: 13.8, carbs: 44.9, fat: 29.4 },
  { id: "olive_oil", name: "Olive oil", kcal: 884, protein: 0.0, carbs: 0.0, fat: 100.0 },
  { id: "vegetable_oil", name: "Vegetable/canola oil", kcal: 884, protein: 0.0, carbs: 0.0, fat: 100.0 },
  { id: "coconut_oil", name: "Coconut oil", kcal: 862, protein: 0.0, carbs: 0.0, fat: 100.0 },
  { id: "cooking_spray", name: "Cooking spray (1-sec spray ≈ 0.3 g)", kcal: 792, protein: 0.0, carbs: 0.0, fat: 88.0 },

  // ---------- Beverages (per 100 ml ≈ 100 g) ----------
  { id: "coffee_black", name: "Coffee (black)", kcal: 2, protein: 0.1, carbs: 0.0, fat: 0.0 },
  { id: "coffee_latte", name: "Latte (with 2% milk)", kcal: 43, protein: 2.8, carbs: 4.0, fat: 1.7 },
  { id: "tea", name: "Tea (unsweetened)", kcal: 1, protein: 0.0, carbs: 0.2, fat: 0.0 },
  { id: "soda_cola", name: "Cola soda", kcal: 41, protein: 0.0, carbs: 10.6, fat: 0.0 },
  { id: "soda_diet", name: "Diet soda", kcal: 0, protein: 0.0, carbs: 0.0, fat: 0.0 },
  { id: "soda_lemon_lime", name: "Lemon-lime soda", kcal: 41, protein: 0.0, carbs: 10.4, fat: 0.0 },
  { id: "orange_juice", name: "Orange juice", kcal: 45, protein: 0.7, carbs: 10.4, fat: 0.2 },
  { id: "apple_juice", name: "Apple juice", kcal: 46, protein: 0.1, carbs: 11.3, fat: 0.1 },
  { id: "lemonade", name: "Lemonade", kcal: 40, protein: 0.0, carbs: 10.4, fat: 0.0 },
  { id: "sports_drink", name: "Sports drink", kcal: 26, protein: 0.0, carbs: 6.5, fat: 0.0 },
  { id: "energy_drink", name: "Energy drink", kcal: 45, protein: 0.4, carbs: 11.0, fat: 0.0 },
  { id: "sweet_tea", name: "Sweet tea", kcal: 36, protein: 0.0, carbs: 9.3, fat: 0.0 },
  { id: "hot_chocolate", name: "Hot chocolate (with milk)", kcal: 77, protein: 3.5, carbs: 10.7, fat: 2.3 },
  { id: "smoothie_fruit", name: "Fruit smoothie (typical)", kcal: 58, protein: 1.0, carbs: 13.5, fat: 0.3 },
  { id: "coconut_water", name: "Coconut water", kcal: 19, protein: 0.7, carbs: 3.7, fat: 0.2 },

  // ---------- Snacks & sweets ----------
  { id: "dark_chocolate", name: "Dark chocolate (70–85% cacao)", kcal: 598, protein: 7.8, carbs: 45.9, fat: 42.6 },
  { id: "milk_chocolate", name: "Milk chocolate", kcal: 535, protein: 7.7, carbs: 59.4, fat: 29.7 },
  { id: "chocolate_chip_cookie", name: "Chocolate chip cookies", kcal: 488, protein: 5.1, carbs: 64.6, fat: 24.0 },
  { id: "oreo_type_cookie", name: "Chocolate sandwich cookies", kcal: 480, protein: 4.5, carbs: 72.0, fat: 20.0 },
  { id: "brownie", name: "Brownie", kcal: 466, protein: 6.2, carbs: 50.0, fat: 29.0 },
  { id: "donut_glazed", name: "Donut (glazed)", kcal: 421, protein: 5.1, carbs: 47.6, fat: 23.4 },
  { id: "muffin_blueberry", name: "Blueberry muffin", kcal: 377, protein: 5.3, carbs: 46.5, fat: 19.0 },
  { id: "cake_chocolate", name: "Chocolate cake (frosted)", kcal: 389, protein: 4.1, carbs: 56.5, fat: 17.5 },
  { id: "apple_pie", name: "Apple pie", kcal: 237, protein: 1.9, carbs: 34.0, fat: 11.0 },
  { id: "cheesecake", name: "Cheesecake", kcal: 321, protein: 5.5, carbs: 25.5, fat: 22.5 },
  { id: "potato_chips", name: "Potato chips (plain, salted)", kcal: 536, protein: 7.0, carbs: 52.9, fat: 34.6 },
  { id: "tortilla_chips", name: "Tortilla chips", kcal: 497, protein: 7.2, carbs: 63.6, fat: 23.4 },
  { id: "pretzels", name: "Pretzels (hard)", kcal: 381, protein: 10.0, carbs: 79.8, fat: 3.5 },
  { id: "popcorn", name: "Popcorn (air-popped)", kcal: 387, protein: 12.9, carbs: 77.8, fat: 4.5 },
  { id: "popcorn_buttered", name: "Popcorn (movie-style, buttered)", kcal: 500, protein: 8.0, carbs: 56.0, fat: 28.0 },
  { id: "cheese_puffs", name: "Cheese puffs", kcal: 558, protein: 5.5, carbs: 54.0, fat: 36.0 },
  { id: "granola_bar", name: "Granola bar (chewy)", kcal: 419, protein: 6.3, carbs: 67.0, fat: 14.5 },
  { id: "fruit_snacks", name: "Fruit snacks (gummy)", kcal: 333, protein: 0.5, carbs: 82.0, fat: 0.2 },
  { id: "gummy_bears", name: "Gummy bears", kcal: 325, protein: 6.9, carbs: 77.0, fat: 0.1 },
  { id: "candy_bar_choc_peanut", name: "Chocolate peanut candy bar", kcal: 497, protein: 9.5, carbs: 59.0, fat: 25.0 },
  { id: "jello", name: "Gelatin dessert", kcal: 62, protein: 1.2, carbs: 14.2, fat: 0.0 },
  { id: "pudding_chocolate", name: "Chocolate pudding (ready-to-eat)", kcal: 120, protein: 2.1, carbs: 20.4, fat: 3.5 },
  { id: "beef_jerky", name: "Beef jerky", kcal: 410, protein: 33.2, carbs: 11.0, fat: 25.6 },
  { id: "rice_krispie_treat", name: "Crisped rice treat", kcal: 400, protein: 3.0, carbs: 80.0, fat: 7.0 },
  { id: "honey", name: "Honey", kcal: 304, protein: 0.3, carbs: 82.4, fat: 0.0 },
  { id: "sugar", name: "Sugar (white)", kcal: 387, protein: 0.0, carbs: 100.0, fat: 0.0 },
  { id: "maple_syrup", name: "Maple syrup", kcal: 260, protein: 0.0, carbs: 67.0, fat: 0.1 },
  { id: "jam", name: "Jam / fruit preserves", kcal: 278, protein: 0.4, carbs: 68.9, fat: 0.1 },

  // ---------- Prepared & restaurant-style meals ----------
  { id: "pizza_cheese", name: "Cheese pizza (regular crust)", kcal: 266, protein: 11.4, carbs: 33.3, fat: 9.7 },
  { id: "pizza_pepperoni", name: "Pepperoni pizza (regular crust)", kcal: 298, protein: 12.9, carbs: 34.0, fat: 12.4 },
  { id: "hamburger", name: "Hamburger (single patty, with bun)", kcal: 254, protein: 12.3, carbs: 27.3, fat: 10.5 },
  { id: "cheeseburger", name: "Cheeseburger (single patty, with bun)", kcal: 282, protein: 14.4, carbs: 25.8, fat: 13.5 },
  { id: "french_fries", name: "French fries", kcal: 312, protein: 3.4, carbs: 41.4, fat: 15.0 },
  { id: "onion_rings", name: "Onion rings (fried)", kcal: 407, protein: 4.6, carbs: 46.5, fat: 22.7 },
  { id: "chicken_sandwich_fried", name: "Fried chicken sandwich", kcal: 279, protein: 14.0, carbs: 26.0, fat: 13.0 },
  { id: "grilled_cheese", name: "Grilled cheese sandwich", kcal: 350, protein: 12.5, carbs: 30.0, fat: 20.0 },
  { id: "blt_sandwich", name: "BLT sandwich", kcal: 240, protein: 9.5, carbs: 22.5, fat: 12.5 },
  { id: "pbj_sandwich", name: "Peanut butter & jelly sandwich", kcal: 350, protein: 11.0, carbs: 42.0, fat: 16.0 },
  { id: "turkey_sandwich", name: "Turkey sandwich (with mayo)", kcal: 220, protein: 12.0, carbs: 25.0, fat: 8.0 },
  { id: "burrito_bean_cheese", name: "Bean & cheese burrito", kcal: 220, protein: 8.5, carbs: 30.5, fat: 7.5 },
  { id: "burrito_chicken", name: "Chicken burrito", kcal: 190, protein: 11.5, carbs: 22.5, fat: 6.5 },
  { id: "taco_beef", name: "Beef taco (hard shell)", kcal: 226, protein: 12.9, carbs: 18.7, fat: 11.6 },
  { id: "quesadilla_cheese", name: "Cheese quesadilla", kcal: 320, protein: 13.0, carbs: 28.0, fat: 17.5 },
  { id: "spaghetti_meat_sauce", name: "Spaghetti with meat sauce", kcal: 130, protein: 6.5, carbs: 17.5, fat: 3.9 },
  { id: "lasagna", name: "Lasagna (with meat)", kcal: 135, protein: 8.1, carbs: 12.8, fat: 5.6 },
  { id: "fried_rice_chicken", name: "Chicken fried rice", kcal: 165, protein: 7.5, carbs: 22.0, fat: 5.2 },
  { id: "lo_mein", name: "Lo mein noodles (with vegetables)", kcal: 145, protein: 5.5, carbs: 22.5, fat: 3.8 },
  { id: "orange_chicken", name: "Orange chicken (takeout-style)", kcal: 235, protein: 13.0, carbs: 24.0, fat: 9.5 },
  { id: "sushi_california", name: "California roll", kcal: 150, protein: 4.5, carbs: 26.0, fat: 3.0 },
  { id: "chicken_pot_pie", name: "Chicken pot pie", kcal: 220, protein: 6.5, carbs: 21.5, fat: 12.0 },
  { id: "meatloaf", name: "Meatloaf", kcal: 205, protein: 15.5, carbs: 6.5, fat: 13.0 },
  { id: "chili_con_carne", name: "Chili con carne (with beans)", kcal: 105, protein: 7.5, carbs: 9.5, fat: 4.4 },
  { id: "soup_chicken_noodle", name: "Chicken noodle soup", kcal: 36, protein: 1.9, carbs: 4.5, fat: 1.1 },
  { id: "soup_tomato", name: "Tomato soup (with water)", kcal: 30, protein: 0.8, carbs: 6.6, fat: 0.3 },
  { id: "soup_broccoli_cheddar", name: "Broccoli cheddar soup", kcal: 95, protein: 3.5, carbs: 6.5, fat: 6.3 },
  { id: "caesar_salad_chicken", name: "Chicken Caesar salad (with dressing)", kcal: 127, protein: 10.5, carbs: 3.5, fat: 8.0 },
  { id: "potato_salad", name: "Potato salad", kcal: 143, protein: 2.7, carbs: 11.2, fat: 10.0 },
  { id: "deviled_egg", name: "Deviled eggs", kcal: 200, protein: 10.5, carbs: 1.5, fat: 16.8 },
  { id: "egg_roll", name: "Egg roll (fried)", kcal: 250, protein: 7.0, carbs: 25.5, fat: 13.0 },
  { id: "corn_dog", name: "Corn dog", kcal: 250, protein: 8.5, carbs: 26.0, fat: 12.5 },
  { id: "burrito_bowl_chicken", name: "Chicken burrito bowl (rice, beans, salsa)", kcal: 130, protein: 9.0, carbs: 15.0, fat: 3.8 },
  { id: "poke_bowl", name: "Poke bowl (tuna, rice)", kcal: 120, protein: 8.5, carbs: 16.0, fat: 2.5 },
  { id: "breakfast_burrito", name: "Breakfast burrito (egg, cheese, sausage)", kcal: 215, protein: 10.0, carbs: 18.5, fat: 11.0 },

  // ---------- Condiments & sauces ----------
  { id: "ketchup", name: "Ketchup", kcal: 101, protein: 1.0, carbs: 25.8, fat: 0.1 },
  { id: "mustard", name: "Mustard (yellow)", kcal: 60, protein: 3.7, carbs: 5.8, fat: 3.3 },
  { id: "mayo", name: "Mayonnaise", kcal: 680, protein: 1.0, carbs: 0.6, fat: 74.8 },
  { id: "mayo_light", name: "Mayonnaise (light)", kcal: 238, protein: 0.4, carbs: 9.2, fat: 22.2 },
  { id: "ranch", name: "Ranch dressing", kcal: 430, protein: 1.2, carbs: 5.9, fat: 44.5 },
  { id: "italian_dressing", name: "Italian dressing", kcal: 240, protein: 0.4, carbs: 9.9, fat: 21.9 },
  { id: "vinaigrette", name: "Balsamic vinaigrette", kcal: 299, protein: 0.3, carbs: 12.0, fat: 27.4 },
  { id: "bbq_sauce", name: "BBQ sauce", kcal: 172, protein: 0.8, carbs: 40.8, fat: 0.6 },
  { id: "hot_sauce", name: "Hot sauce", kcal: 11, protein: 0.5, carbs: 1.8, fat: 0.4 },
  { id: "soy_sauce", name: "Soy sauce", kcal: 53, protein: 8.1, carbs: 4.9, fat: 0.6 },
  { id: "teriyaki_sauce", name: "Teriyaki sauce", kcal: 89, protein: 5.9, carbs: 15.6, fat: 0.0 },
  { id: "marinara", name: "Marinara / pasta sauce", kcal: 51, protein: 1.4, carbs: 7.5, fat: 1.5 },
  { id: "alfredo_sauce", name: "Alfredo sauce", kcal: 180, protein: 3.0, carbs: 5.5, fat: 16.0 },
  { id: "gravy", name: "Gravy (brown, prepared)", kcal: 45, protein: 1.2, carbs: 5.0, fat: 2.2 },
  { id: "guacamole", name: "Guacamole", kcal: 155, protein: 2.0, carbs: 8.0, fat: 13.5 },
  { id: "tartar_sauce", name: "Tartar sauce", kcal: 260, protein: 0.8, carbs: 12.0, fat: 23.0 },
  { id: "sriracha", name: "Sriracha sauce", kcal: 93, protein: 1.9, carbs: 19.2, fat: 0.9 },
  { id: "relish", name: "Sweet pickle relish", kcal: 130, protein: 0.4, carbs: 35.1, fat: 0.5 },
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = BUILTIN_FOODS;
} else {
  window.BUILTIN_FOODS = BUILTIN_FOODS;
}
